server:
  port: 9526

spring:
  application:
    name: sc-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service_route1 #sc-user-service_route1               #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8820                #匹配后提供服务的路由地址
          predicates:
            - Path=/**                      # 断言，路径相匹配的进行路由
        - id: flder-image-service_route2 #sc-user-service_route1               #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8081                #匹配后提供服务的路由地址
          predicates:
            - Path=/**                      # 断言，路径相匹配的进行路由
